services:
  mysql:
    image: mysql
    ports:
      - "3306:3306" # "entrada_de_fora:entrada_de_dentro"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
